// Boareskyr bridge fallout
// THANK YOU JASTEY! <3 
/* activate - no The Boareskyr Bridge Scene mod installed */
IF
	OR(2) InParty(Myself) Global("C#BrandockJoined","GLOBAL",2)
  !See([ENEMY])
  See(Player1) 
	!StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
	GlobalGT("bd_plot","global",294) //after it happened
	GlobalLT("chapter","global",10) // not if game went on
	AreaCheck("bd2000")
	!InMyArea("bdireni")
	!InMyArea("bdfist24")
	Global("C#Brandock_c#stff24_10","GLOBAL",0) // no interjection from tbbs
	Global("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",0)
THEN
	RESPONSE #100
		SetGlobal("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",1)
END

/* initiate */
IF
	OR(2) InParty(Myself) Global("C#BrandockJoined","GLOBAL",2)
  !See([ENEMY])
  See(Player1) 
	!StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  Global("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",1)
THEN
  RESPONSE #100
    RealSetGlobalTimer("C#BrandockDialogTimer","GLOBAL",C#BRANDOCK_TIMER_SOD)
    StartDialogNoSet(Player1)
END

/* after the sign incident at the Boareskyr bridge */
/* activate - in case The Boareskyr Bridge mod run */
IF
	OR(2) InParty(Myself) Global("C#BrandockJoined","GLOBAL",2)
	!RealGlobalTimerNotExpired("C#BrandockDialogTimer","GLOBAL")
	!See([ENEMY])
	See(Player1) 
	!StateCheck(Myself,CD_STATE_NOTVALID)
	!StateCheck(Player1,CD_STATE_NOTVALID)
	CombatCounter(0)
	GlobalGT("bd_plot","global",294) //after it happened
	OR(2)
		Global("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",2) //quick reaction line run
		Global("C#Brandock_c#stff24_10","GLOBAL",1) // interjection from tbbs run
	GlobalLT("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",3)
THEN
	RESPONSE #100
		SetGlobal("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",3)
END



/* initiate */
IF
	OR(2) InParty(Myself) Global("C#BrandockJoined","GLOBAL",2)
  !See([ENEMY])
  See(Player1) 
	!StateCheck(Myself,CD_STATE_NOTVALID)
  !StateCheck(Player1,CD_STATE_NOTVALID)
  CombatCounter(0)
  Global("C#Brando_SoDBoareskyrBridgeScene","GLOBAL",3)
THEN
  RESPONSE #100
    RealSetGlobalTimer("C#BrandockDialogTimer","GLOBAL",C#BRANDOCK_TIMER_SOD)
    StartDialogNoSet(Player1)
END
